name: uni_track
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.1+2

environment:
  sdk: ^3.10.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Das hier hinzuf√ºgen
    sdk: flutter

  flutter_slidable: ^4.0.3
  gap: ^3.0.1
  google_fonts: ^6.3.2
  hidden_drawer_menu: ^3.0.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  provider: ^6.1.5+1
  shared_preferences: ^2.5.3
  slide_to_act: ^2.0.2
  table_calendar: ^3.2.0
  url_launcher: ^6.3.2
  image_picker: ^1.0.4
  tutorial_coach_mark: ^1.3.3
  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.14.4
  change_app_package_name: ^1.5.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "icon/icon_ios.png"
  adaptive_icon_background: "#2196f3"  # Hintergrundfarbe
  adaptive_icon_foreground: "icon/app_icon.png"
  remove_alpha_ios: true


flutter:
  uses-material-design: true
